name: movie_collections
description: "Movie Collection"
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.6.1
dependencies:
  cherry_toast: ^1.12.0
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  getwidget: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  intl: ^0.20.2
  media_kit: ^1.1.11
  media_kit_libs_video: ^1.0.5
  media_kit_video: ^1.2.5
  mime: ^2.0.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  than_pkg: ^1.6.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter_launcher_icons:
  # commmand flutter pub get dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/cover.webp"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
