name: mc_v2
description: "movie စုဆောင်းရတာ ကြိုက်နှစ်သက်တဲ့ သူတွေအတွက်"
version: 1.0.2
publish_to: none

environment:
  sdk: ^3.6.1
dependencies:
  cherry_toast: ^1.12.0
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.6.0
  dio: ^5.8.0+1
  expandable_text: ^2.3.0
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.6+2
  flutter_riverpod: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  media_kit: ^1.2.0
  media_kit_libs_video: ^1.0.6
  media_kit_video: ^1.3.0
  real_path_file_selector: ^0.1.0
  t_widgets: ^0.0.1
  than_pkg: ^2.2.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  change_app_package_name: ^1.4.0
  # dart run change_app_package_name:main [com.new.package.name]
  
flutter_launcher_icons:
  # commmand dart run flutter_launcher_icons
  android: "launcher_icon"
  image_path: "assets/logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
